magnetization:
  num_modes: [78,96,128]
  dim_latent: 256
  num_hidden_layers: 3
  init_omega: 410.0
  hidden_omega: 50.0

coil_sensitivity:
  num_modes: [64,96]
  dim_latent: 256
  num_hidden_layers: 3
  init_omega: 350.0
  hidden_omega: 50.0
